# App
spring.application.name=ubi-voyance-backend
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ubivoyance
spring.datasource.username=balvindersingh
spring.datasource.password= 9868
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File upload limit
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB